export default {
  actors: [
    "Chris Evans",
    "Tom Holland",
    "Tobby Maguire",
    "Leonardo Dicaprio",
    "Will Smith",
    "Chris Hemsworth",
    "Dwayne Johnson",
    "Tom Cruise",
    "Tom Hanks",
    "Denzel Washington",
    "Ryan Reynolds",
    "Hugh Jackman",
    "Brad Pitt",
    "Matthew Mcconaughey",
    "Kevin Hart",
    "Nicolas Cage",
    "Al Pacino",
    "Robert De Niro",
    "Christian Bale",
    "Charlize Theron",
  ],
  animals: [
    "Donkey",
    "Leopard",
    "Dog",
    "Polar bear",
    "Rabbit",
    "Pigeon",
    "Dolphin",
    "Eagle",
    "Goat",
    "Tiger",
    "Cheetah",
    "Gorilla",
    "Giraffe",
    "Cat",
    "Lion",
    "Elephant",
    "Monkey",
    "Giant Panda",
    "Fish",
    "Horse",
  ],
  jobs: [
    "Teacher",
    "Doctor",
    "Police Officer",
    "Developer",
    "Firefighter",
    "Scientist",
    "Enginner",
    "Artist",
    "Nurse",
    "Baker",
    "Waiter",
    "Farmer",
    "Soldier",
    "Detective",
    "Cashier",
    "Butcher",
    "Musician",
    "Business man",
    "Office worker",
    "Tour guide",
  ],
  countries: [
    "Argentina",
    "Australia",
    "Morocco",
    "Brazil",
    "Norway",
    "New Zealand",
    "Canada",
    "USA",
    "Russia",
    "Egypt",
    "Saudi Arabia",
    "France",
    "Syria",
    "Switzerland",
    "Turkey",
    "Iceland",
    "Ukraine",
    "United Kingdom",
    "Lithuania",
    "Japan",
  ],
  sports: [
    "Basketball",
    "Tennis",
    "Soccer",
    "Running",
    "Volleyball",
    "Swimming",
    "Boxing",
    "Golf",
    "Cycling",
    "Kickboxing",
    "Wrestling",
    "American football",
    "Chess",
  ],
  food: [
    "Rice",
    "Pizza",
    "Cheese",
    "Sausages",
    "Hamburger",
    "Cake",
    "Bread",
    "Eggs",
    "Cupcake",
    "Cookies",
    "French Fries",
    "Ice cream",
    "Pasta",
    "Honey",
    "Donuts",
  ],
};
